#https://www.glassdoor.co.uk/Job/us-data-science-jobs-SRCH_IL.0,2_IN1_KO3,15.htm
country_max: 266

search-terms:
  - data-scientist
  - software-engineer
  - data-analyst
  - research-scientist
  - business-analyst
  - product-manager
  - project-manager
  - data-engineer
  - statistician
  - dba
  - database-engineer
  - machine-learning-engineer

jobs-ids-filename: jobs_ids.txt

headers:
  User-Agent:
    Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_1)
    AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.97 Safari/537.36